name: flutter_showcase_2
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  get_it: ^7.6.4
  logger: ^2.0.2+1
  dartz: ^0.10.1
  equatable: ^2.0.5
  geolocator: ^11.0.0
  intl: ^0.19.0
  adaptive_theme: ^3.4.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.0
  smooth_page_indicator: ^1.1.0
  go_router: ^13.1.0
  flutter_bloc: ^8.1.5
  flutter_native_splash: ^2.4.0
  firebase_auth: ^4.19.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  carousel_slider: ^4.2.1
  marquee: ^2.2.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:


  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true


  assets:
    - lib/assets/


